# Site wide configuration

title: opinions are my own...
locale: en_US
url: http://ttimbers.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Tiffany Timbers
  avatar: https://avatars1.githubusercontent.com/u/6865016
  bio: "#datascientist #teacher #genomicist #neuroscientist #jackofalltrades #masterofafew"
  email: tiffany.timbers@gmail.com
  disqus-shortname:
  twitter: TiffanyTimbers
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ttimbers
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: tiffany-timbers-27a45631
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
